import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";

const poppins = Poppins(
  {
    weight: ["100", "200", "400", "500", "600", "800"]
  }
)

export const metadata = {
  title: {
    default:"Care Bridge",
    template:"% | Care Bridge"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        
          <Navbar></Navbar>
        
        <main className="">
          {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
