import AllServices from '@/components/home/AllServices';
import React from 'react';
export const metadata = {
  title:"All Services",
  description: "Generated by create next app",
};
const page = () => {
    return (
        <div>
            <AllServices></AllServices>
        </div>
    );
};

export default page;